config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
  root 'home#index'
  #home controller routes besically for home static page
  resources :contact
	resources :home do
		collection do
			# get :quick_view
		end
	end

  
  #routes for about
  resources :abouts, :path =>"/about-me"
  #routes for blog
  resources :blogs do
    collection do
      get :get_list
      get :get_cat
      get :new_subscriber
      get :model
      post :review_create
    end
    member do
      get :tag
    end
  end
  #routes for projects
  resources :project do
    collection do
      # get :quick_view
    end
  end

  get "/quick_view"=>"home#quick_view",:as=>'quick_view'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include BlogSolr
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :new, :destroy]
  # before_action :set_blog_view, only:[:show]
 # add_breadcrumb "home", :root_path
 #before_save :hello

 # def set_blog_view
 #    BlogPost.set_view_count()
 # end
  # GET /blogs
  # GET /blogs.json
  def index
    @title= 'SH - Blog - Index'
    @subscriber = BlogSubscriber.new
    if params[:search].present?
      @search = search_solr(params[:search])
      @blogs_list = @search.results
      @scarch_text = params[:search]
    else
      @blogs_list = BlogPost.where("status = ?",true).order('view_count DESC').paginate(:page => params[:page], :per_page => 5)
      #@blogs_list = BlogPost.where('created_at >= ? AND status = ?', Time.now-30.days, true).order("id desc").paginate(:page => params[:page], :per_page => 5)
    end
    #@blogs_list = Kaminari.paginate_array(@blogs_list).page(params[:page]).per(1)
    @blog_paralux_img = StaticPageImage.where("img_type=?","blog_paralax").last
    set_meta_tags description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work"
    set_meta_tags keywords: %w[Blog Sumantas_Blog Ruby Rails CSS JAVAScript Jquiry Web Bootstrap Ruby_On_Rails_Blog]
    set_meta_tags canonical: "http://www.sumantahazra.info/blogs"
    #@blogs_populer = BlogPost.where("status = ?",true).order('view_count DESC').page params[:page]
    set_meta_tags og: {
      title:    'SH - Blog - Index',
      type:     'Blog index',
      url:      "http://www.sumantahazra.info",
      description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work"
      #image:     @blogs_list.first.cover_pic.url(:thumb)
      # video:    {
      # director: 'http://www.imdb.com/name/nm0000881/',
      # writer:   ['http://www.imdb.com/name/nm0918711/', 'http://www.imdb.com/name/nm0177018/']
      # }
    }
    set_meta_tags image_src: "#{ActionController::Base.helpers.asset_url('pofile_pic.jpg')}"
    set_meta_tags author: "Sumanta Hazra"
     set_meta_tags twitter: {
      card:  "Blog",
      description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work",
      title: "SH - Blog - Index",
        # image: {
        # _:      @blog.cover_pic.url(:thumb),
        # width:  100,
        # height: 100,
        # }
    }
    set_meta_tags article: {
      section:           'Sumanta Blog',
      tag:               "Tech blog"
    }
    respond_to do |f|
      f.html
      f.js
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @title= 'SH - Blog - '+@blog.title
    set_meta_tags description:  @blog.short_desc
    set_meta_tags author: "Sumanta Hazra"
    set_meta_tags image_src: @blog.cover_pic.url(:thumb)
    set_meta_tags canonical: "http://www.sumantahazra.info/blogs/#{@blog.slug}"
    @blog.set_blog_view()
    set_meta_tags og: {
      title:    @blog.title,
      type:     'Blog, Article',
      site_name: "Sumanta Hazra info And Blog",
      url:      "http://www.sumantahazra.info/blogs/#{@blog.slug}",
      image:    @blog.cover_pic.url(:thumb),
      description: @blog.short_desc
      # video:    {
      # director: 'http://www.imdb.com/name/nm0000881/',
      # writer:   ['http://www.imdb.com/name/nm0918711/', 'http://www.imdb.com/name/nm0177018/']
      # }
    }
    set_meta_tags twitter: {
      card:  "Blog",
      description: @blog.short_desc,
      title: @blog.title,
        image: {
        _:      @blog.cover_pic.url(:thumb),
        width:  100,
        height: 100,
        }
    }
    set_meta_tags article: {
      published_time:    @blog.created_at,
      modified_time:     @blog.updated_at,
      section:           'Sumanta Blog',
      tag:               "Tech blog"
    }
    @review_new = Review.new
    @my_choice = BlogPost.where('created_at >= ? AND status = ?', Time.now-2.days, true).limit(10)
    @populer_blog = @blogs_list = BlogPost.where("status = ?",true).order('view_count DESC').limit(10)
  end

  # GET /blogs/new
  def new
    @blog = BlogPost.new
    @blog.blog_images.build
    set_meta_tags nofollow: 'googlebot'
    set_meta_tags nofollow: true
  end

  #review save
  def review_create
    if params[:review][:blog_post_id].present?
     @blog = BlogPost.find(params[:review][:blog_post_id])
      if verify_recaptcha(model: @blog) && @blog.reviews.create(review_params)
        flash[:success] = "Thank you for review. Your review require approval"
        redirect_back fallback_location: root_path
      else
        flash[:error] = "Sorry!! review can not be create now"
        redirect_back fallback_location: root_path
      end
    else
      flash[:error] = "Sorry!! review can not be create now"
      redirect_back fallback_location: root_path
    end
  end

  #model popup
  def model
    puts "model js"
    @review_new = Review.new
    @blog_id = params[:b_id] if params[:b_id].present?
    @blog = BlogPost.find(@blog_id) if @blog_id.present?
    @title = params[:value]
    respond_to do |format|
      format.js #If it's a js request this line tell rails to look for new_release.js.erb in your views directory
    end
  end

  #new subscriber

  def new_subscriber
    puts "hello sumanta ===================>"
    if params[:name].present? && params[:email].present?
      name = params[:name]
      email = params[:email]
      @sub_check = BlogSubscriber.where("email = ?",params[:email]).last
      if @sub_check.blank?
        new_subscriber = BlogSubscriber.new
        new_subscriber.name = name
        new_subscriber.email = email
        if new_subscriber.save
          @result = true
          ApplicationMailer.send_subscriber_email(new_subscriber.email,"Blog Subscribtion confirmation mail",new_subscriber.name).deliver
        end
      else
        @result = false
      end
    end
  end
  #tag paths
  def tag
    @tag =  BlogCatTag.friendly.find(params[:id])
    @title= "SH - Blog - Scarch by #{@tag.name}"
    @blogs_list = @tag.blog_posts.paginate(:page => params[:page], :per_page => 5)
     set_meta_tags description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work: tag #{@tag.name}"
    set_meta_tags keywords: %w[Blog Sumantas_Blog Ruby Rails CSS JAVAScript Jquiry Web Bootstrap Ruby_On_Rails_Blog]
    set_meta_tags canonical: "http://www.sumantahazra.info/blogs"
    #@blogs_populer = BlogPost.where("status = ?",true).order('view_count DESC').page params[:page]
    set_meta_tags og: {
      title:    "SH - Blog - Scarch by #{@tag.name}",
      type:     'Blog index',
      url:      "http://www.sumantahazra.info",
      description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work: Scarch by #{@tag.name}"
      #image:     @blogs_list.first.cover_pic.url(:thumb)
      # video:    {
      # director: 'http://www.imdb.com/name/nm0000881/',
      # writer:   ['http://www.imdb.com/name/nm0918711/', 'http://www.imdb.com/name/nm0177018/']
      # }
    }
    set_meta_tags image_src: "http://www.sumantahazra.info/assets/pofile_pic.jpg"
    set_meta_tags author: "Sumanta Hazra"
     set_meta_tags twitter: {
      card:  "Blog",
      description: "Sumanta Hazra Ruby on Rails Developer. Blog is a section here i write blogs based on new technologies witch i learn thorugh my work",
      title: "SH - Blog - Scarch by #{@tag.name}",
        # image: {
        # _:      @blog.cover_pic.url(:thumb),
        # width:  100,
        # height: 100,
        # }
    }
    set_meta_tags article: {
      section:           'Sumanta Blog',
      tag:               "Tech blog"
    }
  end


  #get blog list

  def get_list
    if params[:blog_req_type] == "recent"
      @blogs_list = BlogPost.where('created_at >= ? AND status = ?', Time.now-30.days, true).order("id desc").paginate(:page => params[:page], :per_page => 5)#.page params[:page]
        @pagenate = params[:paginate]
      #@test = "recent"
    elsif params[:blog_req_type] == "populer"
      puts "in populer"
      @blogs_list = BlogPost.where("status = ?",true).order('view_count DESC').paginate(:page => params[:page], :per_page => 5)#.page params[:page]
      #@test = "populer"
      @pagenate = params[:paginate]
    end
  end
  # GET /blogs/1/edit
  def edit
  end


   def get_cat
    exams = BlogCatTag.select([:name,:id]).where("name like ? AND c_type=?","%#{params[:name]}%","tag").limit(10)
    result = exams.collect do |t|
      {
        nm: t.name,
        id: t.id
      }
    end
     respond_to do |format|
      format.json {render :json=>{:results=>result}}
    end
    end
  # POST /blogs
  # POST /blogs.json
  def create
    @blog = BlogPost.new(blog_params)
    # blog_cove_img = BlogImage.new
    # blog_cove_img.pic = open(params[:blog_cover_pic])
    #blog_cove_img.save
    #@blog.blog_images << params[:pic]
    @added_tags = BlogCatTag.where("id in (?)",params[:tags])
    @blog.blog_cat_tags << @added_tags
    respond_to do |format|
      if @blog.save
        @blog.update_column(:status, true)
        format.html { redirect_to blog_path(@blog), notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
    set_meta_tags nofollow: 'googlebot'
    set_meta_tags nofollow: true
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_path(@blog), notice: 'Blog was successfully updated.' }

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog_list.html.erb
  <div class="row">
  <%#=@test%>
      <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
        <%=render "blog_post"%>
      </div>
      <div id="page_links">
      	<center>
			<%= will_paginate @blogs_list%>
		</center>
	  </div>
      
    </div>
   
<style type="text/css">
.loader {
  border: 5px solid #f3f3f3;
  border-radius: 50%;
  border-top: 5px solid blue;
  border-bottom: 5px solid blue;
  width: 30px;
  height: 30px;
  margin-top: 20px;
  text-align: center;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}




	.index-cover{
		width: 100%;
		margin-top: 25px;
	}
	.title{
		margin-top:20px;
		font-size: 20px;
		padding-bottom: 20px;
	}
	.left-side-bar{
		background-color: #000;
		min-height: 500px;
	}
	.tags{
		margin-bottom: 10px;
		margin-top: 10px;
	}
	.tags-anch{
		color: gray;
		/*text-decoration: underline;*/
		font-size: 15px;
		text-transform: capitalize;
		/*word-spacing: 10px;*/
	}
	.hole_div{
		padding: 5px;
		padding-bottom: 20px;
	}
	.view_class{
		padding: 10px;
		float: right;
	}
</style>

app/views/blogs/_blog_post.html.erb
<% @blogs_list.each do |xy|%>
          <div class="row hello_appand">
	          <div class="hole_div">
		          <div class="col-md-2"><%=image_tag xy.cover_pic.url(:thumb),:class=>"index-cover"%></div>
		          <div class="col-md-10">
		            <div class="title">
		            <%= link_to xy.title, blog_path(xy) %>
		            </div>
		            <div class="short_desc">
		              <span><%=raw xy.short_desc%>[...]</span>
		            </div>
		             <div class="tags">
		             Tags: 
	            	<%xy.blog_cat_tags.each_with_index do |x,index|%>
	            		<a href=<%=tag_blog_path(x.slug)%> class="tags-anch"><%=x.name%></a>
	            		<%if index+1 != xy.blog_cat_tags.count%>
	        				,
	       				<%end%>
	            	<%end%>
		            </div>
		            <div style="padding: 5px;color: gray;"> 
		            	<span style="margin-right: 20px;"><%= time_ago_in_words(xy.created_at) unless xy.created_at.blank? %> ago</span>
		            	<span>View count <%=xy.view_count%></span>
		            <%if admin_user_signed_in?%>
		            <%=link_to "Edit Blog", edit_blog_path(xy),:class=> "btn btn-primary view_class"%>
		            <%end%>
		            <%=link_to "View Blog", blog_path(xy),:class=> "btn btn-danger view_class"%>
		            </div>
		          </div>
		          </div>
	        </div>

        <%end%>
        <div id="blog_list2"></div>

        <script type="text/javascript">
        	// $(document).ready(function(){
        		//$('.loader').remove();
        	// });
        </script>

app/views/blogs/_blog_share.html.erb
<!-- <a class="fb-share" href="#" onclick="
  window.open(
    'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent('http://www.sumantahazra.info/blogs/<%=@blog.slug%>'), 
    'facebook-share-dialog', 
    'width=626,height=436'); 
  return false;">
  <span class="fb-share-icon"></span><span class="fb-share-text">Share</span>
</a>



<style type="text/css">

</style> -->
<div id="share-buttons">
    <div class="row">
    <!-- Buffer -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="https://bufferapp.com/add?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/buffer.png" alt="Buffer" />
	    </a>
    </div>
    <!-- Digg -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.digg.com/submit?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/diggit.png" alt="Digg" />
	    </a>
    </div>
    <!-- Email -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="mailto:?Subject=Simple Share Buttons&amp;Body=I%20saw%20this%20and%20thought%20of%20you!%20 http://www.sumantahazra.info/blogs/<%=@blog.slug%>">
	        <img src="https://simplesharebuttons.com/images/somacro/email.png" alt="Email" />
	    </a>
 		</div>
    <!-- Facebook -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.facebook.com/sharer.php?u=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/facebook.png" alt="Facebook" />
	    </a>
    </div>
    <!-- Google+ -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="https://plus.google.com/share?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/google.png" alt="Google" />
	    </a>
    </div>
    <!-- LinkedIn -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/linkedin.png" alt="LinkedIn" />
	    </a>
    </div>
    <!-- Pinterest -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());">
	        <img src="https://simplesharebuttons.com/images/somacro/pinterest.png" alt="Pinterest" />
	    </a>
	  </div>
    
    <!-- Print -->
    <div class="col-md-3 col-xs-6 all_btn">
    <a href="javascript:;" onclick="window.print()">
        <img src="https://simplesharebuttons.com/images/somacro/print.png" alt="Print" />
    </a>
    </div>
    <!-- Reddit -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://reddit.com/submit?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>&amp;title=<%=@blog.title%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/reddit.png" alt="Reddit" />
	    </a>
    </div>
    <!-- StumbleUpon-->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.stumbleupon.com/submit?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>&amp;title=<%=@blog.title%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/stumbleupon.png" alt="StumbleUpon" />
	    </a>
    </div>
    <!-- Tumblr-->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.tumblr.com/share/link?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>&amp;title=<%=@blog.title%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/tumblr.png" alt="Tumblr" />
	    </a>
    </div>
    <!-- Twitter -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="https://twitter.com/share?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>&amp;text=<%=@blog.title%>&amp;hashtags=Sumanta_blog Rubu_on_rails" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/twitter.png" alt="Twitter" />
	    </a>
    </div>
    <!-- VK -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://vkontakte.ru/share.php?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/vk.png" alt="VK" />
	    </a>
    </div>
    <!-- Yummly -->
    <div class="col-md-3 col-xs-6 all_btn">
	    <a href="http://www.yummly.com/urb/verify?url=http://www.sumantahazra.info/blogs/<%=@blog.slug%>&amp;title=<%=@blog.title%>" target="_blank">
	        <img src="https://simplesharebuttons.com/images/somacro/yummly.png" alt="Yummly" />
	    </a>
	  </div>
	  </div>
</div>
<style type="text/css">
 
#share-buttons img {
width: 70px;
padding: 5px;
border: 0;
box-shadow: 0;
display: inline;
}
.all_btn{
	margin: 10px;
}
 
</style>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%#= link_to 'Show', @blog %> |
<%#= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<div class="parallax">
<div style="background-color: rgba(0,0,0,0.7);min-height: 200px;">
<!-- <div style="height: 50px;position: fixed;"></div> -->
<div class="row">
  <div class="col-md-3 col-xs-1"></div>
  <div class="col-md-6 col-xs-10">
  <br>
    <div class="search_form">
      <h2 style="color: #fff;">Advance Search: <span style="color:red;font-size: 15px;">Beta Version</span></h2>
      <%=form_tag blogs_path,:method=>:get do%>
         <div style="width:70%;float: left;">
         <%=text_field_tag :search,@scarch_text, :class=>"form-control",:placeholder=>"Enter Your Scarch text"%></div>
         <div style="width:30%;float: left;"><div style=""></div><%=submit_tag "Submit", :class=>"btn btn-primary"%></div>
      <%end%>
    </div>
  </div>
  <div class="col-md-3 col-xs-1"></div>
</div>
  <div class="row" style="position: relative;right: 10px;right: 10%;
    top: 20px;float: right;color: #fff;z-index: 1;">
    <h2>Sumanta's Blogs</h2>
  </div>
  </div>
</div>
<%#=cktext_area_tag "hello",""%>
<div style="">
  <div id="blog_list_hole">
    <div class="row">
  <div class="col-md-2 col-lg-2 col-sm-2 hidden-xs left-side-bar">
    <div id="tabs">
      <!-- <img class="img-circle2 img-responsive" src="/assets/pofile_pic.jpg"> -->
      <%=image_tag "pofile_pic.jpg", :class=>"img-circle2 img-responsive"%>
      <h2>Filters</h2>
      <div class="blog-ul">
        <li class="blog-sidebar-li most_populer blog-active">Populer</li>
        <li class="blog-sidebar-li most_recent">Most Recent</li>
        <li class="blog-sidebar-li my_choice">My Choise</li>
      </div>
    </div>
  </div>
  <div class="col-md-7 col-lg-7 col-sm-7 col-xs-12">
    <div id="blog_list">
     <%=render :partial => "blogs/blog_list",:object=>@blogs_list%>
     </div>
  </div>
  <div class="col-md-3 col-lg-3 col-sm-3 col-xs-12">
    <%=render "blogs/subscriber_form"%>
  </div>
</div>
   
  </div>

</div>


<%#= link_to 'New Blog', new_blog_path %>
<style type="text/css">
.search_form{
  width: 100%;
}


  .parallax {
    /* The image used */
    background-image: url("<%=@blog_paralux_img.img_url.url(:large)%>");

    /* Set a specific height */
    min-height: 200px; 
    background-size: cover;
    /* Create the parallax scrolling effect */
    /*background-attachment: fixed;*/
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    
}

.left-side-bar{
  background-color: #EAEDED;
}
.btn-li{
  margin-bottom: 10px;
}
.img-circle2{
  width: 100%;
  padding: 10px;
}
.blog-sidebar-li{
  /*height: 5px;*/
  background-color: white;
  margin: 5px;
  
}
.blog-active{
  border-right: 5px solid blue;
  border-left: 5px solid blue;
  background-color: #ABEBC6 ;
}
.blog-ul li{
  list-style: none;
  padding: 3px;
  cursor: pointer;
}
@media only screen and (max-device-width: 1024px) {
    .parallax {
        background-attachment: scroll;
    }
}
</style>
 <script>
  // $( function() {
  //   $( "#tabs" ).tabs();
  // } );
  $(document).ready(function(){
    // for latest blogs
    $(".most_recent").click(function(){
      $(".blog-ul li").removeClass("blog-active");
      $(this).addClass("blog-active");
      $.ajax({type: "get",
          url: "/blogs/get_list",
          data:  {"blog_req_type": "recent"}    
        });

    });
    //for populer blog
    $(".most_populer").click(function(){
      $(".blog-ul li").removeClass("blog-active");
      $(this).addClass("blog-active");
      $.ajax({type: "get",
          url: "/blogs/get_list",
          data:  {"blog_req_type": "populer"}    
        });
    });
  });
  </script>

app/views/blogs/new.html.erb
<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
	<div class="contaner-fluid hole_blog">
		
		<div class="row main-blog">
			<div class="col-md-9 col-lg-9 col-xs-12">
				<div class="text-center">
					<h1 class="blog_title"><%=@blog.title%></h1>
				</div>
				<div class="text-blog-div">
					<p class="blog-text">
						<%=raw @blog.desc%>
					</p>
				</div>
				<div class="blog-tags">
					<span>Tags:</span>
					<%array_new_for_tags = Array.new%>
						<%@blog.blog_cat_tags.each_with_index do |x,index|%>
						<%array_new_for_tags.push(x.name)%>
	       		 <a href=<%=tag_blog_path(x.slug)%> class="tags-anch"><%=x.name%></a>
	       			 <%if index+1 != @blog.blog_cat_tags.count%>
	       					 ,
	       				 <%end%>
	       				 
	      		<%end%>
	      		<%set_meta_tags keywords: array_new_for_tags%>
				</div>
				
				<div id="model" ></div>
				<div class="give_comment"><b><%=@blog.reviews.count%></b><span style="color: gray;">&nbsp; Comments</span><span style="float: right;">
					<button class="btn btn-primary common-btn" value="Review">Leave a comment</button>
				</span></div>
				<%= render 'comments_show'%>
				<%#@blog_id = @blog.id%>
				<%#=render "review_form"%>
			</div>
			<div class="col-md-3 col-lg-3 col-xs-12 all_di">
				<%=render :partial=> "blogs/subscriber_form"%>
				<%= render :partial=>"populer_recent_blog"%>
				<%= render :partial=>"review" %>
			</div>
		</div>
	</div>
<style type="text/css">
	.give_comment{
		padding: 20px;
		background-color: #D8DBE1;
		font-size: 20px;
		border-radius: 5px;
	}
	.main-blog{
		margin-top: 20px;
	}
	.hole_blog{
		margin-top: 20px;
		padding-left: 30px;
		padding-right: 30px;
	}
	.blog_title{
		font-size: 40px;
		text-transform: capitalize;
		font-weight: 900;
	}
	.blog-text{
		line-height: 1.5em;
	}
	.text-blog-div{
		margin-top: 30px;
	}
	.blog-tags{
		padding: 20px;
	}
	@media only screen and (max-device-width: 480px) {
		.hole_blog{
			margin-top: 20px;
			padding-left: 5px;
			padding-right: 5px;
		}
	}
</style>

<div id="fb-root"></div>
<script>
//facebook like button api

// (function(d, s, id) {
// 	console.log("It works on each visit!");
//   var js, fjs = d.getElementsByTagName(s)[0];
//   if (d.getElementById(id)) return;
//   js = d.createElement(s); js.id = id;
//   js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
//   fjs.parentNode.insertBefore(js, fjs);
// }(document, 'script', 'facebook-jssdk'));

// $( document ).on('turbolinks:load', function() {
//   console.log("It works on each visit!")
// });
</script>



<%#= link_to 'Edit', edit_blog_path(@blog) %> 
<%#= link_to 'Back', blogs_path %>