config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
  root 'home#index'
  #home controller routes besically for home static page
  resources :contact
	resources :home do
		collection do
			# get :quick_view
		end
	end

  
  #routes for about
  resources :abouts, :path =>"/about-me"
  #routes for blog
  resources :blogs do
    collection do
      get :get_list
      get :get_cat
      get :new_subscriber
      get :model
      post :review_create
    end
    member do
      get :tag
    end
  end
  #routes for projects
  resources :project do
    collection do
      # get :quick_view
    end
  end

  get "/quick_view"=>"home#quick_view",:as=>'quick_view'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authorize, only: [:edit, :update, :new, :destroy]
	#before_action :set_layout
	# def set_layout
	# 	if !admin_user_signed_in?
	# 	  self.class.layout false 
	# 	else
	# 	  self.class.layout 'application'
	# 	end
	# end
  def index
  	@title= 'Sumanta Hazra profile - Home'
  	@all_products = Project.where('id is not null').order('id DESC')
  	@all_img =  StaticPageImage.where("id is not null")
    @populer_blog = BlogPost.where("status = ?",true).order('view_count DESC').limit(6)
    @doc_cv = DocumentDatum.first
    set_meta_tags image_src: "#{ActionController::Base.helpers.asset_url('pofile_pic.jpg')}"
    set_meta_tags description: "I am a Web App developer. I build basically web apps based on Ruby On Rails."
      set_meta_tags og: {
      title:    'SH profile - Home',
      type:     'Sumanta Info',
      url:      "http://www.sumantahazra.info",
      description: "I am a Web App developer. I build basically web apps based on Ruby On Rails.",
      image:    "#{ActionController::Base.helpers.asset_url('pofile_pic.jpg')}"
      # video:    {
      # director: 'http://www.imdb.com/name/nm0000881/',
      # writer:   ['http://www.imdb.com/name/nm0918711/', 'http://www.imdb.com/name/nm0177018/']
      # }
    }
    set_meta_tags author: "Sumanta Hazra"
     set_meta_tags twitter: {
      card:  "Info",
      description: "I am a Web App developer. I build basically web apps based on Ruby On Rails.",
      title: "SH profile - Home",
        image: {
        _:      "#{ActionController::Base.helpers.asset_url('pofile_pic.jpg')}",
        width:  100,
        height: 100,
        }
    }
    set_meta_tags article: {
      section:           'Sumanta Hazra Info',
      tag:               "Sumanta Hazra Info || Blog"
    }

  end
  def quick_view
  	puts "helooooooooooooooooooooooooooooooooooooo"
  	@doc_cv = DocumentDatum.first
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<div style="margin-top: 100px;"></div>
<div id="footer">
    <div class="container-fluid ft-cont">
        <div class="row">
            
            <br>
              <div class="col-md-4">
                <center>
                  <img src="<%=asset_url('programmer.jpg')%>" class="img-circle" alt="the-brains">
                  <br>
                  <h4 class="footertext">Programmer</h4>
                  <p class="footertext">You can thank all the crazy programming here to this guy.<br>
                </center>
              </div>
              <div class="col-md-4">
                <center>
                  <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">
                  <br>
                  <h4 class="footertext">Artist</h4>
                  <p class="footertext">All the images here are hand drawn by this man.<br>
                </center>
              </div>
              <div class="col-md-4">
                <center>
                  <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">
                  <br>
                  <h4 class="footertext">Designer</h4>
                  <p class="footertext">This pretty site and the copy it holds are all thanks to this guy.<br>
                </center>
              </div>
            </div>
            
    </div>
    <div class="last-ft-div">
    <center>
            <p class="footertext">Copyright 2017</p>
            </center>
          </div>
</div>
<script type="text/javascript">
$(".alert-success").fadeOut(10000);
$(".alert-danger").fadeOut(10000);
$(".alert").fadeOut(10000);
</script>

app/views/home/_home_footer.html.erb
<footer>
  <div class="centered clearfix">
    <div class="footer-logo">
       <div class="footer-contact">
       <h3><a href="/contact">Contact</a></h3>
       <p><a href="mailto:">hazrasumanta@gmail.com</a></p>
       <p><a href="tel:">+91 - 9040451287</a></p>
       <p><a href="/about-me">Anjanadri Complex, Tulshi Theatre Road,<br />Bngalore, Marathahalli.<br/> State: Karnataka, <br/> pin:560037 India</a></p>
    </div>
    </div>
   
    <div class="footer-navigation">
      <div class="footer-links-holder">
        <h3><a href="/blogs">BLOGS</a></h3>
        <ul class="footer-links">
          <li><a href="/blogs">Recent Blogs</a></li>
          <li><a href="/blogs">Populer Blogs</a></li>
         <!--  <li><a href="">Page Title 3</a></li>
          <li><a href="">Page Title 4</a></li> -->
        </ul>
      </div>
      <!-- <div class="footer-links-holder">
        <h3><a href="">Section 2</a></h3>
        <ul class="footer-links">
          <li><a href="">Page Title 1</a></li>
          <li><a href="">Page Title 2</a></li>
          <li><a href="">Page Title 3</a></li>
          <li><a href="">Page Title 4</a></li>
        </ul>
      </div> -->
      <div class="footer-links-holder">
        <h3><a href="">Quick Access</a></h3>
        <ul class="footer-links">
          <li><a href="/contact">Contact Me</a></li>
          <li><a href="/about-me">About Me</a></li>
          <li><a href="/project">Projects</a></li>
          <!-- <li><a href="">Page Title 4</a></li> -->
        </ul>
      </div>

    </div>
               <div class="footer-social-icons">
    <h4 class="_14">Follow us on</h4>
    <ul class="social-icons">
        <li><a href="https://www.facebook.com/hazrasumanta" target="_blank" class="social-icon"> <i class="fa fa-facebook"></i></a></li>
        <li><a href="https://twitter.com/HAZRASUMANTA" target="_blank" class="social-icon"> <i class="fa fa-twitter"></i></a></li>
        <!-- <li><a href="" class="social-icon"> <i class="fa fa-rss"></i></a></li>
        <li><a href="" class="social-icon"> <i class="fa fa-youtube"></i></a></li> -->
        <li><a href="https://www.linkedin.com/in/sumanta-hazra-8857884a/" target="_blank" class="social-icon"> <i class="fa fa-linkedin"></i></a></li>
        <li><a href="https://plus.google.com/u/1/112453037456613291535" target="_blank" class="social-icon"> <i class="fa fa-google-plus"></i></a></li>
    </ul>
</div>
  </div>
  <div class="bottom-bar">
      All Rights Reserved © 2017 <!-- | <a href="">Privacy Policy</a> | <a href="">Terms of Service</a> -->
  </div>
</footer>
<script type="text/javascript">
  $(function() {
  $('.footer-links-holder h3').click(function () {
    $(this).parent().toggleClass('active');
  });
});
</script>
<style type="text/css">
  .social-icons{
    display: flex;
  }
  .social-icons li{
    margin: 10px;
    font-size: 20px;
  }
</style>

app/views/home/_index.html.haml
%div
	=render :partial => 'intro_index_dix'

app/views/home/_intro_index_dix.html.erb
<!-- 
<div class="parallax">
	<div class="parallax-text">
		<div class="span-text-fst-div text-center contaner">
		<center>
			<span class="fst-div-text" style="min-height: 170px;"></span>
			<span class="fst-div-text" style="font-size: 50px;font-family: 'Acme', sans-serif;">Oh, hi there!!</span>
			<span class="fst-div-text">I am <span style="color: red;">Sumanta</span></span>
			<span class="fst-div-text">I love designing And Buliding creative, Fuctional websites.</span>
			</center>
		</div>
	</div>
</div> -->
<div class="banner-div">
<%=render :partial=> "home/new_image_slide"%>
</div>
<div class="row hole_home" style="position: absolute;">
		<%#=render :partial=> "home/my_profile_div_mobile"%>
<%#=render :partial=> "home/my_profile_div_desktop"%>
<%= render :partial=> 'home/projects'%> 
<%= render :partial=> 'home/populer_blog'%> 
<%= render :partial=> 'home/home_footer'%> 
</div>
<%#fast_div_img = @all_img.where("img_type = ?","first-div").last%>
<style type="text/css">

	.span-text-fst-div{
		
		font-size: 30px;
		color: #fff;
		
		font-family: 'Crete Round', serif;
		/*position: absolute;
		top: 40%;
		left: 40%;*/
			}
	.fst-div-text{
		display: -webkit-box;
	}
	/*font-family: 'Roboto', sans-serif;
	font-family: 'Anton', sans-serif;
	font-family: 'Acme', sans-serif;
	font-family: 'Crete Round', serif;*/
	/*.hole_home{
		background-color: #666666;;
	}*/
	#footer{
		display: none;
	}
	@media only screen and (max-width: 480px) {
		.header {
			width:100% !important;
			left: 0px !important;
			top: 0px !important;
			background-color: rgba(255, 255, 255, 1.0) !important;
		}
	}
	.hole_home{
		background-color: #fff;
		/*position: relative;*/
		top: 100%;
	}
	.header {
    z-index:0;
    width:98%;
    left: 12px;
    top: 12px;
    z-index:999;
    position:absolute;
    background-color: rgba(255, 255, 255, 0.7);
    z-index: 999;
    color: #fff;
    -webkit-transition: all 0.8s;
    -moz-transition: all 0.8s;
    transition: all 0.8s;
    -webkit-transform: translateY(0%);
    -moz-transform: translateY(0%);
    transform: translateY(0%);
  }

  .header.affix {
    background-color:#fff;
    width:100%;
    top:0;
    left: 0;
    right:0;
    padding:0;
    margin:0;
    position: fixed;
    z-index: 1030;
    -webkit-transition: all 0.8s;
    -moz-transition: all 0.8s;
    transition: all 0.8s;

  }
  .navbar-default{
  	border:none;
  }
  .navbar-border {
  	border:none;
	}
	.hello-head{
		margin-top: 0px !important;
	}
</style>
<script type="text/javascript">
	$(document).ready(function(){
		$(".header").affix({
			offset: {
				top: 100
			}

		});
	});
</script>

app/views/home/_my_profile_div_desktop.html.erb
<div class="row" style="padding:20px;margin-top: 30px;margin-bottom: 20px;">
	<div class="col-md-4 col-xs-12 text-center">
		<%=link_to '<i class="fa fa-info-circle" aria-hidden="true"></i> About Me'.html_safe ,"/about-me",:class=>"btn btn-warning btn-lg btn-wire"%>
	</div>
	<div class="col-md-4 col-xs-12 text-center">
		<%=link_to '<i class="fa fa-eye" aria-hidden="true"></i> View Profile'.html_safe ,@doc_cv.document.url,:class=>"btn btn-warning btn-lg btn-wire"%>
	</div>
	<div class="col-md-4 col-xs-12 text-center">
		<%=link_to '<i class="fa fa-download" aria-hidden="true"></i> Download Profile'.html_safe ,@doc_cv.document.url,:class=>"btn btn-warning btn-lg btn-wire", download: "Sumanta profile"%>
	</div>
</div>

<div class="introduction">
	<div class="text-ceneter">
	<center>
		<h2 class="figcaption2" style="font-family: 'Acme', sans-serif;font-size:30px;">Introduction</h2>
		</center>
	</div>
	<div class="row complite_chat">
		<div class="col-md-3 col-lg-3 col-sm-3 col-xs-12 profile_image_div text-center">
			<!-- <img class="img-circle2" src="/assets/pofile_pic.jpg"> -->
			<%=image_tag "pofile_pic.jpg", :class=>"img-circle2" %>
		</div>
		<div class="col-md-9 col-lg-9 col-sm-9 col-xs-12 profile_image_div">
			<div class="chat_div">
				<p style="padding: 20px;">
					I am a Web App developer. I build basically web apps based on <strong>Ruby On Rails</strong>, there i created many website on same. I love to design websites as well as fuctional implementations. I have experience of web apps development on Rails different version. Technologies is used in different defferent development <strong>Ruby, CSS3, Jquiry, Javascript, json, Mysql(DataBase),PostgreSQL(Database), HTML, Bootstrap</strong>.
					<br>
					<br>
					Web Apps I create All are <strong>Full Responsive</strong>. It can be adopt in many different devise environment. 
					<br>
					<br> I have complited my <strong>Master Of Computer Application</strong> form <strong>KIIT Univesity</strong>
					<%=link_to "know more...", "/about-me"%>
				</p>
			</div>
		</div>
	</div>
</div>


<style type="text/css">
	/*.introduction{
		background-color: #fff;
		margin: 20px;
		padding: 20px;
		border-radius: 10px;
	}*/
	.img-circle2 {
		border-radius: 10px;
		height: 200px;
		width: 200px;
	}
	.profile_image_div{
		
	}
/*	.chat_div {
    background: #f0ecec ;
    border-radius: 10px;
    width:100%;
    min-height:150px;
    position: relative;
    display: inline-block;
    background-color:  #f0ecec ;
}
.chat_div:before {
    content:"";
    position: absolute;
    height: 0px;
    width: 0px;
    top: 60px;
    left: -29px; /* 1px buffer for zooming problems while rendering*/
  /*  border-width: 15px;
    border-color: transparent  #f0ecec transparent transparent;
    border-style: solid;
}*/
	.complite_chat{
		margin: 20px;
		max-height: 300px;
		margin-top: 50px;
	}
</style>

app/views/home/_my_profile_div_mobile.html.haml
%div.container-fluid.mobile_prodiv
	%center
		%h2.figcaption2{:style=>"font-family: 'Acme', sans-serif;font-size:30px;"}
			Intoduction
	=image_tag("/assets/pofile_pic.jpg",:class=>"iange_profile")
	.profile_main_div
		%span.text_span
			I am a Web App developer. I build basically web apps based on 
			%strong 
				Ruby On Rails
			, there i created many website on same. I love to design websites as well as fuctional implementations. I have experience of web apps development on Rails different version. Technologies is used in defferent development 
			%strong
				Ruby, CSS3, Jquiry, Javascript,Json, Mysql(DataBase),
				%br
				PostgreSQL(Database), HTML, Bootstrap.
			%br
			%br
			Web Apps I create All are 
			%strong
				Full Responsive.
				It can be adopt in many different devise environment. 
			%br
			%br 
			I have complited my 
			%strong
				Master Of Computer Application
			form 
			%strong
				KIIT Univesity
			=link_to "know more...", "/about-me"



:css
	.iange_profile{
		height:50%;
		width:100%;
		margin-top:20px;
	}
	.text_span{
		font-family: 'Roboto', sans-serif;
		font-size:20px;
		line-height: 2em;
	}
	.mobile_prodiv{
		background-color:  #eee8e8;
	}
	.profile_main_div{
		min-height:100px;
		margin-top:10px;
		margin-bottom:10px;
	}

app/views/home/_new_image_slide.html.erb
  <ul class="cb-slideshow">
            <li><span>Image 01</span><div><h3>Web·Design</h3></div></li>
            <li><span>Image 02</span><div><h3>Responsive·Desing</h3></div></li>
            <li><span>Image 03</span><div><h3>Technical·Blog</h3></div></li>
            <li><span>Image 04</span><div><h3>Ruby·On·Rails</h3></div></li>
            <li><span>Image 05</span><div><h3>Bussiness·Logics</h3></div></li>
            <li><span>Image 06</span><div><h3>Server·Config</h3></div></li>
        </ul>

app/views/home/_populer_blog.html.erb
<section class="wrapper">
    <div class="container-big">
        <div>
            <img src="" class="big-logo"/>
            <center>
    <h2 class="figcaption2" style="font-family: 'Acme', sans-serif;font-size:30px;">Populer Blogs</h2>
    </center>
        </div>
        <div class="content" style="margin-top: 30px;">
            <div class="container">
                <div class="row">
                <%@populer_blog.each do |x|%>
                    <div class="col-xs-12 col-sm-4">
                        <div class="carbox">
                            <a class="img-carbox" href="<%=blog_path(x)%>">
                            <%=image_tag x.cover_pic.url(:medium)%>
                          </a>
                            <div class="carbox-content">
                                <h4 class="carbox-title">
                                    <a href="<%=blog_path(x)%>"> <%=x.title%>
                                  </a>
                                </h4>
                                <p class="">
                                    <%if x.short_desc.present?%>
                                     <%=x.short_desc%>...
                                    <%end%>
                                </p>
                            </div>
                            <div class="carbox-read-more">
                                <a href="<%=blog_path(x)%>" class="btn btn-link btn-block">
                                    Read More
                                </a>
                            </div>
                        </div>
                    </div>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/home/_product_slide_show.html.erb
<!-- <div class="accordian">
  <ul>
  <%#@all_products.each do |x|%>
    <li>
      <div class="image_title">
        <! <a href="#{project_path(x)}"><%#= x.name%></a> -->
        <%#= link_to x.name, project_path(x) %>
      <!-- </div> -->
      <%#= link_to project_path(x) do %>
     <!-- <img src="<%#=x.pic.url(:pslide)%>"> -->
			<%#end%>
    <!-- </li> -->
  <%#end%>
  <!-- </ul> -->
<!-- </div> --> 

<div class="row p_div">
  <%@all_products.each do |x|%>
    <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
      <div class="p_inner_div">
        <img src="<%=x.pic.url(:pslide)%>" class="p_img img-responsive">
        <a href="<%=project_path(x)%>"><h3 style="text-transform: capitalize;"><%= x.name%></h3></a>
        <p class="p_img_div"> <%=x.desc[0..100]%>...</p>
        <a type="button" href="<%=project_path(x)%>"  class="btn btn-outline-success waves-effect">More info</a>
      </div>
    </div>
  <%end%>
</div>

<style type="text/css">
  .p_img{
    height: 50%;
    width: 100%;
    border-radius: 5px;
  }
  .p_div{
    margin-top: 40px;
    margin-left: 0px;
    margin-right: 0px;
  }
  .p_inner_div{
    margin: 10px;
    padding: 5px;
    height: 400px;
    
    background-color:#fff;

  }
  .btn-outline-success {
    border: 2px solid #00C851;
    color: #007E33!important;
    background-color: transparent;
  }
  .p_img_div{
    padding-left: 25px;
    padding-right: 25px;
    text-align: left;
    color:#b9b9b9;
  }
  @media only screen and (max-width: 480px) {
    .p_inner_div{
        padding: 5px;
        height: 380px;
      }
    .projects {
      padding:0px !important;
    }
    .p_img_div{
      padding-left: 0px;
      padding-right: 0px;
    }
    .p_div{
      padding: 5px;
      margin-top: 40px;
    }
    .p_img{
      height: 35%;
      width: 100%;
    }
  }
</style>

app/views/home/_projects.html.haml
%div.projects
	%center
		%span{:style=>"font-family: 'Acme', sans-serif;font-size:30px;",:class=>"figcaption2"}
			My Projects
		
		=render :partial=> 'home/product_slide_show'
		%a{:class=>"btn btn-warning btn-lg btn-wire",:href=>"/project", :role=>"button"}More Projects »
:css
	.projects{
		min-height:600px;
		font-family: 'Roboto', sans-serif;
		background-color: #fff;
	}
	.figcaption2:before,
	.figcaption2:after {
		background-color: gray;
		content: "";
		display: inline-block;
		height: 2px;
		position: relative;
		vertical-align: super;
		width: 15%;
	}
	.btn-wire {
		margin-top: 30px;
		background-color: transparent;
		color: #000;
	}

app/views/home/_under_cons.html.erb
<center>
<img src="http://www.manusamoa.com/images/Under-construction.png">
</center>
<h1>Sorry!! this website is in under construction</h1>
<h4>This domain is booked by Sumanta Hazra.</h4>
<p>Do visit again</p>

app/views/home/about-me.html.erb
<div class="container">
    <div class="row">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel panel-custom">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            <i class="glyphicon glyphicon-plus"></i>
                            Collapsible Group Item #1
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body animated zoomOut">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
    /*
snippet from Animate.css - zoomIn effect
*/
.animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-fill-mode:both;animation-fill-mode:both}.animated.infinite{-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite}.animated.hinge{-webkit-animation-duration:2s;animation-duration:2s
}@-webkit-keyframes zoomIn{0%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}50%{opacity:1}}@keyframes zoomIn{0%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}50%{opacity:1}}.zoomIn{-webkit-animation-name:zoomIn;animation-name:zoomIn}
@-webkit-keyframes zoomOut{0%{opacity:1}50%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}100%{opacity:0}}@keyframes zoomOut{0%{opacity:1}50%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}100%{opacity:0}}.zoomOut{-webkit-animation-name:zoomOut;animation-name:zoomOut}

#accordion .panel-title i.glyphicon{
    -moz-transition: -moz-transform 0.5s ease-in-out;
    -o-transition: -o-transform 0.5s ease-in-out;
    -webkit-transition: -webkit-transform 0.5s ease-in-out;
    transition: transform 0.5s ease-in-out;
}

.rotate-icon{
    -webkit-transform: rotate(-225deg);
    -moz-transform: rotate(-225deg);
    transform: rotate(-225deg);
}

.panel{
    border: 0px;
    border-bottom: 1px solid #30bb64;
}
.panel-group .panel+.panel{
    margin-top: 0px;
}
.panel-group .panel{
    border-radius: 0px;
}
.panel-heading{
    border-radius: 0px;
    color: white;
    padding: 25px 15px;
}
.panel-custom>.panel-heading{
    background-color: #38cc70;
}
.panel-group .panel:last-child{
    border-bottom: 5px solid #2ba659;
}

panel-collapse .collapse.in{
    border-bottom:0;
}
</style>

<script type="text/javascript">
    $(function() {

    function toggleChevron(e) {
        $(e.target)
                .prev('.panel-heading')
                .find("i")
                .toggleClass('rotate-icon');
        $('.panel-body.animated').toggleClass('zoomIn zoomOut');
    }
    
    $('#accordion').on('hide.bs.collapse', toggleChevron);
    $('#accordion').on('show.bs.collapse', toggleChevron);
})


</script>

app/views/home/index.html.erb
<!--here we are rendering another index file as remote of homes different views-->
<%#if admin_user_signed_in? %>
<%= render :partial=>"home/index"%>
<%#else%>
<!--for tempurary under-constraction file -->
<%#= render :partial=>"home/under_cons"%>
<%#end%>

app/views/home/quick_view.html.erb
 <div class="hidden-xs hidden-sm">
  <embed src="<%=@doc_cv.document.url%>" width="100%" height="1000" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html"></div>
<!-- <div class="PDF">
   <object data="<%=@doc_cv.document.url%>" type="application/pdf" width="100%" height="600">
       alt : <a href="<%=@doc_cv.document.url%>">your.pdf</a>
   </object>
</div> -->
<div style="padding: 10px;">
<object data="filename.pdf" type="application/pdf" width="100%" height="100%">
  <p>Your web browser doesn't have a PDF plugin.
  Instead you can <a href="<%=@doc_cv.document.url%>" download>click here to
  download the PDF file.</a></p>
</object></div>