config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  
  root 'home#index'
  #home controller routes besically for home static page
  resources :contact
	resources :home do
		collection do
			# get :quick_view
		end
	end

  
  #routes for about
  resources :abouts, :path =>"/about-me"
  #routes for blog
  resources :blogs do
    collection do
      get :get_list
      get :get_cat
      get :new_subscriber
      get :model
      post :review_create
    end
    member do
      get :tag
    end
  end
  #routes for projects
  resources :project do
    collection do
      # get :quick_view
    end
  end

  get "/quick_view"=>"home#quick_view",:as=>'quick_view'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about_me.rb
class AboutMe < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_cat_tag.rb
class BlogCatTag < ApplicationRecord
  has_and_belongs_to_many :blog_posts
  extend FriendlyId
  friendly_id :name, use: [:slugged,:history]
  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/blog_cat_tags_post.rb
class BlogCatTagsPost < ApplicationRecord
  belongs_to :blog_posts
  belongs_to :blog_cat_tags
end

app/models/blog_image.rb
class BlogImage < ApplicationRecord
  belongs_to :blog_post
  has_attached_file :pic,
	  	:styles   => {
	    :tiny       => "20x20",
	    :thumb      => "200x200",
	    :smalla     => "100x100",
	    :smallb     => "150x150",
	    :medium     => "240x340",
      :pslide     => "500x300",
	    :large      => "1280x720"
  }

   validates_attachment :pic,
    #:presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	# before_save :view_count
	has_many :blog_images
	has_many :reviews, foreign_key: "blog_post_id"
	has_and_belongs_to_many :blog_cat_tags
	  has_attached_file :cover_pic,
	  	:styles   => {
	    :tiny       => "20x20",
	    :thumb      => "200x200",
	    :smalla     => "100x100",
	    :smallb     => "150x150",
	    :medium     => "240x340",
     	:pslide     => "500x300",
	    :large      => "1280x720"
  	}
  	 validates_attachment :cover_pic,
    #:presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
	extend FriendlyId
	  friendly_id :title, use: [:slugged,:history]
	  def should_generate_new_friendly_id?
	    title_changed?
	  end
	  def set_blog_view()
	  	puts "test sumanta"
	  	if self.view_count != nil
	  		v_c = self.view_count
	  		puts "hello check this #{v_c}"
		  	self.update_column(:view_count, v_c + 1)
		  	puts "after upadte #{self.view_count}"
		  else
		  	self.update_column(:view_count,  1)
		 end
	  end

	searchable do
	   text :title , :short_desc
	   integer :id
	   date :created_at
	   boolean :status
	   text :blog_cat_tags do
		   blog_cat_tags.map(&:name)
		 end
		 text :reviews do 
		 	self.reviews.map(&:name)
		 end
		  text :reviews do 
		 	self.reviews.map(&:content)
		end
	end
end

app/models/blog_subscriber.rb
class BlogSubscriber < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
	def self.get_data(data)
		r_data =  Contact.where("c_nme = ?",data)
		return r_data
	end
	
end

app/models/document_datum.rb
class DocumentDatum < ApplicationRecord
	has_attached_file :document
    

	validates_attachment :document,:size => { :in => 0..10.megabytes }, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :technologys
	extend FriendlyId
  friendly_id :m_slug, use: [:slugged,:history]
  def should_generate_new_friendly_id?
    name_changed?
  end
  def m_slug
  	url = ''
  	if self.name.present?
  		url = url + self.name
  		all_tech = Technology.where("project_id = ?",self.id)
  		all_tech.each do |x|
  			url = url + x.name
  		end
  		url
  	else
  		self.name
  	end
 	

  end
	has_attached_file :pic,
	  	:styles   => {
	    :tiny       => "20x20",
	    :thumb      => "200x200",
	    :smalla     => "100x100",
	    :smallb     => "150x150",
	    :medium     => "240x340",
      :pslide     => "500x300",
	    :large      => "1280x720"
  }

   validates_attachment :pic,
    #:presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :blog_post, foreign_key: "blog_post_id"
end

app/models/static_page_image.rb
class StaticPageImage < ApplicationRecord

has_attached_file :img_url,
  	:styles   => {
    :tiny       => "20x20",
    :thumb      => "200x200",
    :smalla     => "100x100",
    :smallb     => "150x150",
    :medium     => "240x340",
    :large      => "1280x720"
  }

   validates_attachment :img_url,
    #:presence => true,
    :size => { :in => 0..10.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :project
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :new, :destroy]
  # GET /abouts
  # GET /abouts.json
  def index
    @title= 'SH - About Me'
    set_meta_tags description: "Hi!! I am Sumanta Hazra. I am from West Bengal(West Midnapore, Daspur). I born in early 90's 1st June. Here you can get to know all my basic details."
    @all_about = AboutMe.where("status = ?",true )
    @first_div = AboutMe.where("title = ?","About me").last
    set_meta_tags keywords: %w[About Section, early life, Early life and family]
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
    @title= 'SH - About Me Show'
  end

  # GET /abouts/new
  def new
    @title= 'SH - About Me New'
    @about = AboutMe.new
  end

  # GET /abouts/1/edit
  def edit
    @title= 'SH - About Me Edit'
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = AboutMe.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to about_path(@about), notice: 'About was successfully created.' }
        #format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to about_path(@about), notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = AboutMe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.fetch(:about_me, {}).permit(:title,:desc,:status)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/abouts/_form.html.erb
<%= simple_form_for @about, :url => { :controller => "abouts", :action => (controller.action_name == "new") ? "create" : "update"  } do |f| %>
  <%= f.error_notification %>
  <div class="row">
  	<div class="col-md-2"></div>
  	<div class="col-md-8">
		  <div class="form-inputs">
		  	<%=f.text_field :title, :class=>"form-control",:placeholder=>"Title" %>
		  </div>
		  <br>
		  <div class="form-inputs">
		  <%=f.cktext_area :desc, :class=>"form-control" %>
		  </div>
		  <br>
		  <div class="form-inputs">
		  <label>Status</label>
		  <%=f.check_box :status%>
		  </div>
	  <div class="form-actions text-center">
	    <%= f.button :submit %>
	  </div>
	  </div>
	  <div class="col-md-2"></div>
  </div>
<% end %>
<script type="text/javascript">
	$(document).ready(function(){
		CKEDITOR.config.height = 400;
	});
</script>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%#= link_to 'Show', @about %> |
<%#= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<div class="header-all">
    <span>About Me</span>
</div>
<div class="row" style="padding-left: 5%;padding-right: 5%;margin-bottom: 30px;">
  <span style="font-size: 15px;">
    <%= raw @first_div.desc if @first_div.present?%>
  </span>
</div>
<div class="container">
    <div class="row">
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <%@all_about.each_with_index do |x,index|%>
            <div class="panel panel-custom">
                <div class="panel-heading" role="tab" id="headingOne">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=index%>" aria-expanded="true" aria-controls="collapse<%=index%>">
                            <i class="glyphicon glyphicon-plus"></i>
                            <%=x.title%>
                        </a>
                    </h4>
                </div>
                <div id="collapse<%=index%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="panel-body animated zoomOut">
                        <span style="text-align: left;"><%=raw x.desc%></span>
                    </div>
                </div>
            </div>
            <%end%>
        </div>
    </div>
</div>

<style type="text/css">
    /*
snippet from Animate.css - zoomIn effect
*/
.animated{-webkit-animation-duration:1s;animation-duration:1s;-webkit-animation-fill-mode:both;animation-fill-mode:both}.animated.infinite{-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite}.animated.hinge{-webkit-animation-duration:2s;animation-duration:2s
}@-webkit-keyframes zoomIn{0%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}50%{opacity:1}}@keyframes zoomIn{0%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}50%{opacity:1}}.zoomIn{-webkit-animation-name:zoomIn;animation-name:zoomIn}
@-webkit-keyframes zoomOut{0%{opacity:1}50%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}100%{opacity:0}}@keyframes zoomOut{0%{opacity:1}50%{opacity:0;-webkit-transform:scale3d(.3,.3,.3);transform:scale3d(.3,.3,.3)}100%{opacity:0}}.zoomOut{-webkit-animation-name:zoomOut;animation-name:zoomOut}

#accordion .panel-title i.glyphicon{
    -moz-transition: -moz-transform 0.5s ease-in-out;
    -o-transition: -o-transform 0.5s ease-in-out;
    -webkit-transition: -webkit-transform 0.5s ease-in-out;
    transition: transform 0.5s ease-in-out;
}

.rotate-icon{
    -webkit-transform: rotate(-225deg);
    -moz-transform: rotate(-225deg);
    transform: rotate(-225deg);
}

.panel{
    border: 0px;
    border-bottom: 1px solid #30bb64;
}
.panel-group .panel+.panel{
    margin-top: 0px;
}
.panel-group .panel{
    border-radius: 0px;
}
.panel-heading{
    border-radius: 0px;
    color: white;
    /*padding: 25px 15px;*/
}
.panel-custom>.panel-heading{
    background-color: #5d7366;
}
.panel-group .panel:last-child{
    border-bottom: 5px solid #6c8274;
}

panel-collapse .collapse.in{
    border-bottom:0;
}
</style>

<script type="text/javascript">
    $(function() {

    function toggleChevron(e) {
        $(e.target)
                .prev('.panel-heading')
                .find("i")
                .toggleClass('rotate-icon');
        $('.panel-body.animated').toggleClass('zoomIn zoomOut');
    }
    
    $('#accordion').on('hide.bs.collapse', toggleChevron);
    $('#accordion').on('show.bs.collapse', toggleChevron);
})


</script>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>